### ISSUE TITLE
How to listen continuously ?

### ISSUE THREAD

**Issue by Xsmael** [EddyVerbruggen/nativescript-speech-recognition#6]
How to listen continuously and get the words as the person speaks ?

**Comment by gtnunes1956** [comment]
Not recommended, unless you are prepared for an uphill struggle with Google (wherein BTW you are not likely to succeed). Unfortunately, ever since Lollipop times they have been very active at attempting to scare away developers from using the Android Speech API for dictation (obviously, in favor of, and due to conflicts with, their own "OK Google" feature, not to mention their paid SR cloud service). Every new release of the OS brings in different behavior and new bugs.  For a taste of the hustle, google "android error_no_match".

**Comment by Xsmael** [comment]
oh no :( all my dreams are now spoiled! Google! grrrr.

**Comment by gtnunes1956** [comment]
@Xsmael, please, do not forget to close this issue.
